// internal/instructions/instructions.go
//
// Discovers ambient agent instructions and composes them into the system
// prompt for every provider.
//
// Discovery order (later overrides earlier when keys collide):
//   1. User global:    ~/.claude/CLAUDE.md, ~/.codex/AGENTS.md
//   2. Project root:   <workdir>/CLAUDE.md, <workdir>/AGENTS.md
//   3. Editor-specific:
//        <workdir>/.cursor/rules/*.md  (Cursor convention)
//        <workdir>/.github/copilot-instructions.md
//   4. Profile skills: from the active routing profile
//
// Each file is wrapped with provenance markers so the agent can tell where
// instructions came from. Composed output is a single Markdown blob, suitable
// for prepending to the continuation contract.

package instructions

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Source — one discovered instruction file.
type Source struct {
	Path     string // absolute path on disk
	Origin   string // "user-global" | "project" | "editor-rule" | "profile-skill"
	Label    string // short human label, e.g. "CLAUDE.md" or "global"
	Bytes    int64
	SHA256   string // first 12 hex chars
	Excluded bool   // true if user disabled this file via config
}

// Composite — the full discovery + composition result.
type Composite struct {
	Sources []Source
	// CombinedMarkdown is the full block ready to prepend to the system prompt.
	CombinedMarkdown string
	// Skills lifted from the active profile (kept separate for visibility).
	Skills []string
}

// DiscoverOptions configures the scan.
type DiscoverOptions struct {
	WorkDir         string
	ProfileSkills   []string
	ProfileContext  string
	IncludeUserHome bool
	// Paths the user explicitly opted out of (absolute paths).
	ExcludedPaths map[string]bool
}

// Discover walks the filesystem and returns a Composite.
// Missing files are silently skipped; permission errors are skipped with no log.
func Discover(opts DiscoverOptions) Composite {
	var sources []Source

	if opts.IncludeUserHome {
		if home, err := os.UserHomeDir(); err == nil {
			sources = append(sources, scanGlobal(home, opts.ExcludedPaths)...)
		}
	}
	if opts.WorkDir != "" {
		sources = append(sources, scanProject(opts.WorkDir, opts.ExcludedPaths)...)
	}

	// Build combined Markdown
	var b strings.Builder
	b.WriteString("# Composed agent context\n\n")
	b.WriteString("_Generated by Relay. Combines user-global rules, project rules, and the active profile._\n\n")

	hadAny := false
	for _, s := range sources {
		if s.Excluded {
			continue
		}
		data, err := os.ReadFile(s.Path)
		if err != nil {
			continue
		}
		hadAny = true
		fmt.Fprintf(&b, "\n---\n## %s\n_Source: `%s` (%s, sha %s)_\n\n",
			s.Label, s.Path, s.Origin, s.SHA256)
		b.Write(data)
		if len(data) == 0 || data[len(data)-1] != '\n' {
			b.WriteString("\n")
		}
	}

	if opts.ProfileContext != "" || len(opts.ProfileSkills) > 0 {
		hadAny = true
		b.WriteString("\n---\n## Active profile\n\n")
		if opts.ProfileContext != "" {
			fmt.Fprintf(&b, "**Context:** %s\n\n", opts.ProfileContext)
		}
		if len(opts.ProfileSkills) > 0 {
			b.WriteString("**Skills emphasised:**\n")
			for _, s := range opts.ProfileSkills {
				fmt.Fprintf(&b, "- %s\n", s)
			}
			b.WriteString("\n")
		}
	}

	if !hadAny {
		return Composite{Sources: sources, Skills: opts.ProfileSkills}
	}

	return Composite{
		Sources:          sources,
		CombinedMarkdown: b.String(),
		Skills:           opts.ProfileSkills,
	}
}

// ─── scan implementations ─────────────────────────────────────────────────────

func scanGlobal(home string, excluded map[string]bool) []Source {
	candidates := []struct {
		rel    string
		origin string
		label  string
	}{
		{".claude/CLAUDE.md", "user-global", "global CLAUDE.md"},
		{".config/claude/CLAUDE.md", "user-global", "global CLAUDE.md (xdg)"},
		{".codex/AGENTS.md", "user-global", "global AGENTS.md"},
		{".config/codex/AGENTS.md", "user-global", "global AGENTS.md (xdg)"},
		{".relay/instructions.md", "user-global", "user Relay rules"},
	}
	var out []Source
	for _, c := range candidates {
		p := filepath.Join(home, c.rel)
		if s, ok := sourceFor(p, c.origin, c.label, excluded); ok {
			out = append(out, s)
		}
	}
	return out
}

func scanProject(workDir string, excluded map[string]bool) []Source {
	var out []Source
	rootCandidates := []struct {
		name  string
		label string
	}{
		{"CLAUDE.md", "project CLAUDE.md"},
		{"AGENTS.md", "project AGENTS.md"},
		{".github/copilot-instructions.md", "Copilot project rules"},
		{".relay/instructions.md", "project Relay rules"},
	}
	for _, c := range rootCandidates {
		p := filepath.Join(workDir, c.name)
		if s, ok := sourceFor(p, "project", c.label, excluded); ok {
			out = append(out, s)
		}
	}

	// Cursor rules — directory of .md files
	cursorDir := filepath.Join(workDir, ".cursor", "rules")
	if entries, err := os.ReadDir(cursorDir); err == nil {
		// Sort for stable order
		names := make([]string, 0, len(entries))
		for _, e := range entries {
			if !e.IsDir() && strings.HasSuffix(strings.ToLower(e.Name()), ".md") {
				names = append(names, e.Name())
			}
		}
		sort.Strings(names)
		for _, n := range names {
			p := filepath.Join(cursorDir, n)
			label := "Cursor rule: " + n
			if s, ok := sourceFor(p, "editor-rule", label, excluded); ok {
				out = append(out, s)
			}
		}
	}

	// Continue rules
	continueRules := filepath.Join(workDir, ".continue", "rules.md")
	if s, ok := sourceFor(continueRules, "editor-rule", "Continue rules", excluded); ok {
		out = append(out, s)
	}

	return out
}

func sourceFor(path, origin, label string, excluded map[string]bool) (Source, bool) {
	info, err := os.Stat(path)
	if err != nil || info.IsDir() || info.Size() == 0 {
		return Source{}, false
	}
	// Skip absurdly large files (>1 MB) — likely not instruction docs
	if info.Size() > 1<<20 {
		return Source{}, false
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return Source{}, false
	}
	sum := sha256.Sum256(data)
	return Source{
		Path:     path,
		Origin:   origin,
		Label:    label,
		Bytes:    info.Size(),
		SHA256:   hex.EncodeToString(sum[:6]),
		Excluded: excluded[path],
	}, true
}
